/* ========================================
   ANA'S COSMETICS - PRODUCTS DATABASE
   ======================================== */

const PRODUCTS = [
  // FACE - FOUNDATION & CONCEALER
  {
    id: 1,
    name: 'Luminous Silk Foundation',
    category: 'Foundation',
    price: 48.00,
    oldPrice: 58.00,
    image: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 342,
    description: 'Luxurious foundation with silk-like finish for all skin types',
    availability: 'In Stock',
    sku: 'LSF-001',
    brand: 'Ana\'s Cosmetics',
    tags: ['foundation', 'face', 'bestseller'],
    discount: 17
  },
  {
    id: 2,
    name: 'Perfect Coverage Concealer',
    category: 'Concealer',
    price: 32.00,
    oldPrice: 42.00,
    image: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd77c65?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 289,
    description: 'Full coverage concealer that lasts all day',
    availability: 'In Stock',
    sku: 'PCC-002',
    brand: 'Ana\'s Cosmetics',
    tags: ['concealer', 'face', 'bestseller'],
    discount: 24
  },
  {
    id: 3,
    name: 'Radiant Glow Primer',
    category: 'Primer',
    price: 38.00,
    oldPrice: null,
    image: 'https://images.unsplash.com/photo-1585708860210-f45e0e69bb2a?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 156,
    description: 'Silky primer that creates the perfect base for makeup',
    availability: 'In Stock',
    sku: 'RGP-003',
    brand: 'Ana\'s Cosmetics',
    tags: ['primer', 'face', 'new'],
    discount: 0
  },
  {
    id: 4,
    name: 'Velvet Powder Foundation',
    category: 'Foundation',
    price: 42.00,
    oldPrice: 52.00,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 198,
    description: 'Lightweight powder foundation for natural coverage',
    availability: 'In Stock',
    sku: 'VPF-004',
    brand: 'Ana\'s Cosmetics',
    tags: ['foundation', 'face'],
    discount: 19
  },
  {
    id: 5,
    name: 'Flawless Setting Spray',
    category: 'Setting Spray',
    price: 28.00,
    oldPrice: 35.00,
    image: 'https://images.unsplash.com/photo-1620024889814-4a2ee0f12ff4?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 267,
    description: 'Long-lasting setting spray for all-day makeup wear',
    availability: 'In Stock',
    sku: 'FSS-005',
    brand: 'Ana\'s Cosmetics',
    tags: ['setting spray', 'face', 'bestseller'],
    discount: 20
  },

  // EYES - EYESHADOW & EYELINER
  {
    id: 6,
    name: 'Luxe Eyeshadow Palette - Neutrals',
    category: 'Eyeshadow',
    price: 55.00,
    oldPrice: 70.00,
    image: 'https://images.unsplash.com/photo-1596554183607-b7f2f989c4d5?w=400&h=400&fit=crop',
    rating: 4.9,
    reviews: 512,
    description: '12 neutral shades with buttery texture and long wear',
    availability: 'In Stock',
    sku: 'LEP-006',
    brand: 'Ana\'s Cosmetics',
    tags: ['eyeshadow', 'eyes', 'bestseller'],
    discount: 21
  },
  {
    id: 7,
    name: 'Precision Eyeliner Pen',
    category: 'Eyeliner',
    price: 22.00,
    oldPrice: 28.00,
    image: 'https://images.unsplash.com/photo-1598084993633-34c4e7a5e0a6?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 234,
    description: 'Ultra-precise felt-tip eyeliner for perfect lines',
    availability: 'In Stock',
    sku: 'PEP-007',
    brand: 'Ana\'s Cosmetics',
    tags: ['eyeliner', 'eyes'],
    discount: 21
  },
  {
    id: 8,
    name: 'Volumizing Mascara',
    category: 'Mascara',
    price: 32.00,
    oldPrice: 42.00,
    image: 'https://images.unsplash.com/photo-1611241893435-3d9195a2d54c?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 401,
    description: 'Buildable mascara for dramatic volume and length',
    availability: 'In Stock',
    sku: 'VM-008',
    brand: 'Ana\'s Cosmetics',
    tags: ['mascara', 'eyes', 'bestseller'],
    discount: 24
  },
  {
    id: 9,
    name: 'Eyebrow Pencil - Dark Brown',
    category: 'Eyebrow',
    price: 18.00,
    oldPrice: 24.00,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 145,
    description: 'Precision eyebrow pencil with fine tip',
    availability: 'In Stock',
    sku: 'EBP-009',
    brand: 'Ana\'s Cosmetics',
    tags: ['eyebrow', 'eyes'],
    discount: 25
  },
  {
    id: 10,
    name: 'Eyeshadow Palette - Jewel Tones',
    category: 'Eyeshadow',
    price: 58.00,
    oldPrice: 75.00,
    image: 'https://images.unsplash.com/photo-1609642527619-8a54b81e01c8?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 289,
    description: '12 rich jewel-toned shades for bold looks',
    availability: 'In Stock',
    sku: 'EJT-010',
    brand: 'Ana\'s Cosmetics',
    tags: ['eyeshadow', 'eyes', 'new'],
    discount: 23
  },

  // LIPS
  {
    id: 11,
    name: 'MAC Matte Lipstick – Ruby Woo (Lipstick)',
    category: 'Lipstick',
    price: 28.00,
    oldPrice: 36.00,
    image: 'https://cdn.fynd.com/v2/falling-surf-7c8bb8/fyprod/wrkr/products/pictures/item/free/original/000000000494434929/fhBtXgY_Kw1A-000000000494434929_1.jpg',
    rating: 4.8,
    reviews: 378,
    description: 'Luxurious velvet matte lipstick with rich color',
    availability: 'In Stock',
    sku: 'VLS-011',
    brand: 'Ana\'s Cosmetics',
    tags: ['lipstick', 'lips', 'bestseller'],
    discount: 22
  },
  {
    id: 12,
    name: 'Glossy Lip Gloss - Champagne',
    category: 'Lip Gloss',
    price: 22.00,
    oldPrice: 28.00,
    image: 'https://images.unsplash.com/photo-1617638924702-92d37f439220?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 267,
    description: 'Shimmering lip gloss with plumping effect',
    availability: 'In Stock',
    sku: 'GLG-012',
    brand: 'Ana\'s Cosmetics',
    tags: ['lip gloss', 'lips'],
    discount: 21
  },
  {
    id: 13,
    name: 'Lip Liner - Nude',
    category: 'Lip Liner',
    price: 16.00,
    oldPrice: 22.00,
    image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 134,
    description: 'Precision lip liner for defined lips',
    availability: 'In Stock',
    sku: 'LLN-013',
    brand: 'Ana\'s Cosmetics',
    tags: ['lip liner', 'lips'],
    discount: 27
  },
  {
    id: 14,
    name: 'Liquid Lipstick - Berry',
    category: 'Lipstick',
    price: 26.00,
    oldPrice: 34.00,
    image: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 245,
    description: 'Long-wearing liquid lipstick with matte finish',
    availability: 'In Stock',
    sku: 'LLS-014',
    brand: 'Ana\'s Cosmetics',
    tags: ['lipstick', 'lips'],
    discount: 24
  },
  {
    id: 15,
    name: 'Lip Balm - Rose',
    category: 'Lip Care',
    price: 14.00,
    oldPrice: null,
    image: 'https://images.unsplash.com/photo-1588195538326-c5b1e62d4b4a?w=400&h=400&fit=crop',
    rating: 4.4,
    reviews: 89,
    description: 'Nourishing lip balm with natural rose scent',
    availability: 'In Stock',
    sku: 'LBR-015',
    brand: 'Ana\'s Cosmetics',
    tags: ['lip care', 'lips', 'new'],
    discount: 0
  },

  // CHEEKS - BLUSH & BRONZER
  {
    id: 16,
    name: 'Silky Blush - Coral Peach',
    category: 'Blush',
    price: 32.00,
    oldPrice: 42.00,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 312,
    description: 'Smooth blush with natural flush finish',
    availability: 'In Stock',
    sku: 'SBC-016',
    brand: 'Ana\'s Cosmetics',
    tags: ['blush', 'cheeks', 'bestseller'],
    discount: 24
  },
  {
    id: 17,
    name: 'Bronzing Powder',
    category: 'Bronzer',
    price: 36.00,
    oldPrice: 46.00,
    image: 'https://images.unsplash.com/photo-1599644995697-76bce4da5c86?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 198,
    description: 'Matte bronzer for natural sun-kissed glow',
    availability: 'In Stock',
    sku: 'BP-017',
    brand: 'Ana\'s Cosmetics',
    tags: ['bronzer', 'cheeks'],
    discount: 22
  },
  {
    id: 18,
    name: 'Highlighter Palette',
    category: 'Highlighter',
    price: 42.00,
    oldPrice: 55.00,
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 289,
    description: '4 luminous highlighter shades for radiant skin',
    availability: 'In Stock',
    sku: 'HP-018',
    brand: 'Ana\'s Cosmetics',
    tags: ['highlighter', 'cheeks', 'bestseller'],
    discount: 24
  },
  {
    id: 19,
    name: 'Cream Blush - Rosy Pink',
    category: 'Blush',
    price: 28.00,
    oldPrice: 36.00,
    image: 'https://images.unsplash.com/photo-1599644992505-b5a0b13e8f2b?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 167,
    description: 'Creamy blush for seamless blending',
    availability: 'In Stock',
    sku: 'CB-019',
    brand: 'Ana\'s Cosmetics',
    tags: ['blush', 'cheeks'],
    discount: 22
  },
  {
    id: 20,
    name: 'Contour Kit',
    category: 'Contour',
    price: 45.00,
    oldPrice: 60.00,
    image: 'https://images.unsplash.com/photo-1599644992505-b5a0b13e8f2b?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 234,
    description: '6 shades for professional contouring',
    availability: 'In Stock',
    sku: 'CK-020',
    brand: 'Ana\'s Cosmetics',
    tags: ['contour', 'cheeks', 'new'],
    discount: 25
  },

  // SKINCARE
  {
    id: 21,
    name: 'Luxury Face Cleanser',
    category: 'Cleanser',
    price: 38.00,
    oldPrice: 48.00,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 201,
    description: 'Gentle yet effective facial cleanser',
    availability: 'In Stock',
    sku: 'LFC-021',
    brand: 'Ana\'s Cosmetics',
    tags: ['skincare', 'cleanser'],
    discount: 21
  },
  {
    id: 22,
    name: 'Hydrating Moisturizer',
    category: 'Moisturizer',
    price: 52.00,
    oldPrice: 68.00,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 345,
    description: 'Rich moisturizer for all skin types',
    availability: 'In Stock',
    sku: 'HM-022',
    brand: 'Ana\'s Cosmetics',
    tags: ['skincare', 'moisturizer', 'bestseller'],
    discount: 24
  },
  {
    id: 23,
    name: 'Vitamin C Serum',
    category: 'Serum',
    price: 65.00,
    oldPrice: 85.00,
    image: 'https://images.unsplash.com/photo-1570194676062-5a3cf44dba0c?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 267,
    description: 'Brightening serum with pure vitamin C',
    availability: 'In Stock',
    sku: 'VCS-023',
    brand: 'Ana\'s Cosmetics',
    tags: ['skincare', 'serum'],
    discount: 24
  },
  {
    id: 24,
    name: 'Anti-Aging Eye Cream',
    category: 'Eye Cream',
    price: 48.00,
    oldPrice: 62.00,
    image: 'https://images.unsplash.com/photo-1596217551529-b60bdf1d6144?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 178,
    description: 'Delicate eye cream to reduce fine lines',
    availability: 'In Stock',
    sku: 'AAE-024',
    brand: 'Ana\'s Cosmetics',
    tags: ['skincare', 'eye cream'],
    discount: 23
  },
  {
    id: 25,
    name: 'Exfoliating Face Mask',
    category: 'Mask',
    price: 42.00,
    oldPrice: 55.00,
    image: 'https://images.unsplash.com/photo-1557322552-cc89b3cb6b1d?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 145,
    description: 'Weekly exfoliating treatment for smooth skin',
    availability: 'In Stock',
    sku: 'EFM-025',
    brand: 'Ana\'s Cosmetics',
    tags: ['skincare', 'mask'],
    discount: 24
  },

  // BRUSHES & TOOLS
  {
    id: 26,
    name: 'Professional Brush Set - 12pc',
    category: 'Brushes',
    price: 85.00,
    oldPrice: 110.00,
    image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 289,
    description: 'Complete brush set with premium synthetic bristles',
    availability: 'In Stock',
    sku: 'PBS-026',
    brand: 'Ana\'s Cosmetics',
    tags: ['brushes', 'tools', 'bestseller'],
    discount: 23
  },
  {
    id: 27,
    name: 'Makeup Sponge - 3 Pack',
    category: 'Sponges',
    price: 16.00,
    oldPrice: 22.00,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
    rating: 4.4,
    reviews: 98,
    description: 'Latex-free makeup sponges for flawless application',
    availability: 'In Stock',
    sku: 'MS-027',
    brand: 'Ana\'s Cosmetics',
    tags: ['sponges', 'tools'],
    discount: 27
  },
  {
    id: 28,
    name: 'Brush Cleaner & Dryer',
    category: 'Tools',
    price: 35.00,
    oldPrice: null,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 123,
    description: 'Electric brush cleaner and dryer',
    availability: 'In Stock',
    sku: 'BCD-028',
    brand: 'Ana\'s Cosmetics',
    tags: ['tools', 'new'],
    discount: 0
  },
  {
    id: 29,
    name: 'Makeup Brush Holder',
    category: 'Storage',
    price: 28.00,
    oldPrice: 36.00,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 87,
    description: 'Elegant brush holder with compartments',
    availability: 'In Stock',
    sku: 'MBH-029',
    brand: 'Ana\'s Cosmetics',
    tags: ['storage', 'tools'],
    discount: 22
  },
  {
    id: 30,
    name: 'Eyelash Curler',
    category: 'Tools',
    price: 18.00,
    oldPrice: 24.00,
    image: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 156,
    description: 'Professional-grade eyelash curler',
    availability: 'In Stock',
    sku: 'EC-030',
    brand: 'Ana\'s Cosmetics',
    tags: ['tools', 'eyes'],
    discount: 25
  },

  // NAIL CARE
  {
    id: 31,
    name: 'Nail Polish - Midnight Black',
    category: 'Nail Polish',
    price: 12.00,
    oldPrice: 16.00,
    image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 134,
    description: 'Long-lasting nail polish with gel-like finish',
    availability: 'In Stock',
    sku: 'NP-031',
    brand: 'Ana\'s Cosmetics',
    tags: ['nail polish', 'nails'],
    discount: 25
  },
  {
    id: 32,
    name: 'Gel Nail Polish - Rose Gold',
    category: 'Gel Polish',
    price: 18.00,
    oldPrice: 24.00,
    image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 201,
    description: 'UV gel polish for salon-quality nails',
    availability: 'In Stock',
    sku: 'GP-032',
    brand: 'Ana\'s Cosmetics',
    tags: ['gel polish', 'nails'],
    discount: 25
  },
  {
    id: 33,
    name: 'Nail File Set',
    category: 'Nail Tools',
    price: 14.00,
    oldPrice: 18.00,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
    rating: 4.4,
    reviews: 76,
    description: 'Professional nail file set with 5 files',
    availability: 'In Stock',
    sku: 'NFS-033',
    brand: 'Ana\'s Cosmetics',
    tags: ['nail tools', 'nails'],
    discount: 22
  },
  {
    id: 34,
    name: 'Cuticle Oil',
    category: 'Nail Care',
    price: 16.00,
    oldPrice: 22.00,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 98,
    description: 'Nourishing cuticle oil with natural ingredients',
    availability: 'In Stock',
    sku: 'CO-034',
    brand: 'Ana\'s Cosmetics',
    tags: ['nail care', 'nails'],
    discount: 27
  },
  {
    id: 35,
    name: 'Nail Art Brush Set',
    category: 'Nail Tools',
    price: 22.00,
    oldPrice: 28.00,
    image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 112,
    description: 'Precision brushes for nail art designs',
    availability: 'In Stock',
    sku: 'NAB-035',
    brand: 'Ana\'s Cosmetics',
    tags: ['nail tools', 'nails'],
    discount: 21
  },

  // FRAGRANCE
  {
    id: 36,
    name: 'Eau de Parfum - Floral',
    category: 'Perfume',
    price: 78.00,
    oldPrice: 98.00,
    image: 'https://images.unsplash.com/photo-1585708860210-f45e0e69bb2a?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 267,
    description: 'Luxurious floral fragrance with long-lasting scent',
    availability: 'In Stock',
    sku: 'EDP-036',
    brand: 'Ana\'s Cosmetics',
    tags: ['perfume', 'fragrance', 'bestseller'],
    discount: 20
  },
  {
    id: 37,
    name: 'Body Mist - Vanilla',
    category: 'Body Mist',
    price: 28.00,
    oldPrice: 36.00,
    image: 'https://images.unsplash.com/photo-1585708860210-f45e0e69bb2a?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 145,
    description: 'Light and refreshing body mist',
    availability: 'In Stock',
    sku: 'BM-037',
    brand: 'Ana\'s Cosmetics',
    tags: ['body mist', 'fragrance'],
    discount: 22
  },
  {
    id: 38,
    name: 'Fragrance Roller - Amber',
    category: 'Fragrance',
    price: 18.00,
    oldPrice: 24.00,
    image: 'https://images.unsplash.com/photo-1585708860210-f45e0e69bb2a?w=400&h=400&fit=crop',
    rating: 4.4,
    reviews: 89,
    description: 'Portable fragrance roller for on-the-go',
    availability: 'In Stock',
    sku: 'FR-038',
    brand: 'Ana\'s Cosmetics',
    tags: ['fragrance', 'new'],
    discount: 25
  }, 
  {
    id: 39,
    name: 'Scented Candle',
    category: 'Home Fragrance',
    price: 32.00,
    oldPrice: 42.00,
    image: 'https://images.unsplash.com/photo-1602591437281-8cea256f6cda?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 178,
    description: 'Premium scented candle with 40-hour burn time',
    availability: 'In Stock',
    sku: 'SC-039',
    brand: 'Ana\'s Cosmetics',
    tags: ['candle', 'home fragrance'],
    discount: 24
  },
  {
    id: 40,
    name: 'Perfume Sampler Set',
    category: 'Perfume',
    price: 45.00,
    oldPrice: 60.00,
    image: 'https://images.unsplash.com/photo-1585708860210-f45e0e69bb2a?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 201,
    description: '5 fragrance samples to discover your favorite',
    availability: 'In Stock',
    sku: 'PS-040',
    brand: 'Ana\'s Cosmetics',
    tags: ['perfume', 'fragrance'],
    discount: 25
  },

  // HAIR CARE
  {
    id: 41,
    name: 'Silk Hair Serum',
    category: 'Hair Serum',
    price: 32.00,
    oldPrice: 42.00,
    image: 'https://images.unsplash.com/photo-1522338503344-6807367a3a95?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 234,
    description: 'Smoothing serum for silky, frizz-free hair',
    availability: 'In Stock',
    sku: 'SHS-041',
    brand: 'Ana\'s Cosmetics',
    tags: ['hair serum', 'hair care'],
    discount: 24
  },
  {
    id: 42,
    name: 'Volumizing Shampoo',
    category: 'Shampoo',
    price: 28.00,
    oldPrice: 36.00,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 167,
    description: 'Lightweight shampoo for fuller, thicker hair',
    availability: 'In Stock',
    sku: 'VS-042',
    brand: 'Ana\'s Cosmetics',
    tags: ['shampoo', 'hair care'],
    discount: 22
  },
  {
    id: 43,
    name: 'Hydrating Conditioner',
    category: 'Conditioner',
    price: 28.00,
    oldPrice: 36.00,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 189,
    description: 'Deep conditioning treatment for dry hair',
    availability: 'In Stock',
    sku: 'HC-043',
    brand: 'Ana\'s Cosmetics',
    tags: ['conditioner', 'hair care'],
    discount: 22
  },
  {
    id: 44,
    name: 'Hair Mask - Repair',
    category: 'Hair Mask',
    price: 35.00,
    oldPrice: 45.00,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 212,
    description: 'Intensive repair mask for damaged hair',
    availability: 'In Stock',
    sku: 'HM-044',
    brand: 'Ana\'s Cosmetics',
    tags: ['hair mask', 'hair care'],
    discount: 22
  },
  {
    id: 45,
    name: 'Dry Shampoo',
    category: 'Dry Shampoo',
    price: 18.00,
    oldPrice: 24.00,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop',
    rating: 4.4,
    reviews: 134,
    description: 'Refreshing dry shampoo for between washes',
    availability: 'In Stock',
    sku: 'DS-045',
    brand: 'Ana\'s Cosmetics',
    tags: ['dry shampoo', 'hair care'],
    discount: 25
  },

  // BODY CARE
  {
    id: 46,
    name: 'Luxe Body Lotion',
    category: 'Body Lotion',
    price: 38.00,
    oldPrice: 48.00,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 201,
    description: 'Silky body lotion with luxurious fragrance',
    availability: 'In Stock',
    sku: 'LBL-046',
    brand: 'Ana\'s Cosmetics',
    tags: ['body lotion', 'body care'],
    discount: 21
  },
  {
    id: 47,
    name: 'Body Scrub - Sugar',
    category: 'Body Scrub',
    price: 32.00,
    oldPrice: 42.00,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 156,
    description: 'Gentle exfoliating body scrub with sugar crystals',
    availability: 'In Stock',
    sku: 'BS-047',
    brand: 'Ana\'s Cosmetics',
    tags: ['body scrub', 'body care'],
    discount: 24
  },
  {
    id: 48,
    name: 'Hand Cream - Rose',
    category: 'Hand Care',
    price: 18.00,
    oldPrice: 24.00,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop',
    rating: 4.4,
    reviews: 112,
    description: 'Nourishing hand cream with rose extract',
    availability: 'In Stock',
    sku: 'HC-048',
    brand: 'Ana\'s Cosmetics',
    tags: ['hand cream', 'body care'],
    discount: 25
  },
  {
    id: 49,
    name: 'Bath Bomb Set',
    category: 'Bath',
    price: 35.00,
    oldPrice: 45.00,
    image: 'https://images.unsplash.com/photo-1602591437281-8cea256f6cda?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 189,
    description: '4 luxurious bath bombs with essential oils',
    availability: 'In Stock',
    sku: 'BB-049',
    brand: 'Ana\'s Cosmetics',
    tags: ['bath bomb', 'body care'],
    discount: 22
  },
  {
    id: 50,
    name: 'Body Oil - Shimmer',
    category: 'Body Oil',
    price: 42.00,
    oldPrice: 55.00,
    image: 'https://images.unsplash.com/photo-1570194676062-5a3cf44dba0c?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 145,
    description: 'Shimmering body oil for luminous skin',
    availability: 'In Stock',
    sku: 'BO-050',
    brand: 'Ana\'s Cosmetics',
    tags: ['body oil', 'body care'],
    discount: 24
  },

  // SETS & BUNDLES
  {
    id: 51,
    name: 'Complete Makeup Starter Kit',
    category: 'Sets',
    price: 125.00,
    oldPrice: 165.00,
    image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 312,
    description: 'Everything you need to start your makeup journey',
    availability: 'In Stock',
    sku: 'CMS-051',
    brand: 'Ana\'s Cosmetics',
    tags: ['sets', 'bestseller'],
    discount: 24
  },
  {
    id: 52,
    name: 'Skincare Essentials Bundle',
    category: 'Sets',
    price: 145.00,
    oldPrice: 190.00,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 234,
    description: 'Complete skincare routine in one bundle',
    availability: 'In Stock',
    sku: 'SEB-052',
    brand: 'Ana\'s Cosmetics',
    tags: ['sets', 'skincare'],
    discount: 24
  },
  {
    id: 53,
    name: 'Lip Collection - 5 Colors',
    category: 'Sets',
    price: 95.00,
    oldPrice: 125.00,
    image: 'https://images.unsplash.com/photo-1565958011504-819a2d6efcc5?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 178,
    description: '5 must-have lipstick shades',
    availability: 'In Stock',
    sku: 'LC-053',
    brand: 'Ana\'s Cosmetics',
    tags: ['sets', 'lips'],
    discount: 24
  },
  {
    id: 54,
    name: 'Eye Makeup Collection',
    category: 'Sets',
    price: 135.00,
    oldPrice: 175.00,
    image: 'https://images.unsplash.com/photo-1596554183607-b7f2f989c4d5?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 201,
    description: 'Complete eye makeup set with palettes and tools',
    availability: 'In Stock',
    sku: 'EMC-054',
    brand: 'Ana\'s Cosmetics',
    tags: ['sets', 'eyes'],
    discount: 23
  },
  {
    id: 55,
    name: 'Luxury Gift Set',
    category: 'Sets',
    price: 185.00,
    oldPrice: 245.00,
    image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=400&h=400&fit=crop',
    rating: 4.9,
    reviews: 289,
    description: 'Premium gift set with bestselling products',
    availability: 'In Stock',
    sku: 'LGS-055',
    brand: 'Ana\'s Cosmetics',
    tags: ['sets', 'gift', 'bestseller'],
    discount: 24
  },

  // ADDITIONAL PRODUCTS
  {
    id: 56,
    name: 'Makeup Remover Wipes',
    category: 'Makeup Remover',
    price: 14.00,
    oldPrice: 18.00,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 123,
    description: 'Gentle makeup remover wipes for sensitive skin',
    availability: 'In Stock',
    sku: 'MRW-056',
    brand: 'Ana\'s Cosmetics',
    tags: ['makeup remover', 'skincare'],
    discount: 22
  },
  {
    id: 57,
    name: 'Toner - Hydrating',
    category: 'Toner',
    price: 35.00,
    oldPrice: 45.00,
    image: 'https://images.unsplash.com/photo-1570194676062-5a3cf44dba0c?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 145,
    description: 'Hydrating toner to balance skin',
    availability: 'In Stock',
    sku: 'TH-057',
    brand: 'Ana\'s Cosmetics',
    tags: ['toner', 'skincare'],
    discount: 22
  },
  {
    id: 58,
    name: 'Face Mist - Rose Water',
    category: 'Face Mist',
    price: 22.00,
    oldPrice: 28.00,
    image: 'https://images.unsplash.com/photo-1620024889814-4a2ee0f12ff4?w=400&h=400&fit=crop',
    rating: 4.4,
    reviews: 98,
    description: 'Refreshing rose water face mist',
    availability: 'In Stock',
    sku: 'FMR-058',
    brand: 'Ana\'s Cosmetics',
    tags: ['face mist', 'skincare'],
    discount: 21
  },
  {
    id: 59,
    name: 'Sunscreen SPF 50',
    category: 'Sunscreen',
    price: 38.00,
    oldPrice: 48.00,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 212,
    description: 'Lightweight daily sunscreen with SPF 50',
    availability: 'In Stock',
    sku: 'SS-059',
    brand: 'Ana\'s Cosmetics',
    tags: ['sunscreen', 'skincare'],
    discount: 21
  },
  {
    id: 60,
    name: 'Night Cream - Repair',
    category: 'Night Cream',
    price: 52.00,
    oldPrice: 68.00,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 267,
    description: 'Rich night cream for overnight repair',
    availability: 'In Stock',
    sku: 'NC-060',
    brand: 'Ana\'s Cosmetics',
    tags: ['night cream', 'skincare', 'bestseller'],
    discount: 24
  }
];

// Get product by ID
function getProductById(id) {
  return PRODUCTS.find(p => p.id === id);
}

// Get products by category
function getProductsByCategory(category) {
  return PRODUCTS.filter(p => p.category === category);
}

// Get all categories
function getCategories() {
  return [...new Set(PRODUCTS.map(p => p.category))].sort();
}

// Search products
function searchProducts(query) {
  const q = query.toLowerCase();
  return PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q) ||
    p.tags.some(tag => tag.toLowerCase().includes(q))
  );
}

// Get featured products
function getFeaturedProducts(limit = 6) {
  return PRODUCTS.filter(p => p.tags.includes('bestseller')).slice(0, limit);
}

// Get new products
function getNewProducts(limit = 6) {
  return PRODUCTS.filter(p => p.tags.includes('new')).slice(0, limit);
}

// Get sale products
function getSaleProducts() {
  return PRODUCTS.filter(p => p.discount > 0).sort((a, b) => b.discount - a.discount);
}
