/* ========================================
   ANA'S COSMETICS - PRODUCTS DATABASE
   ======================================== */

const PRODUCTS = [
  // FACE - FOUNDATION & CONCEALER
  {
    id: 1,
    name: 'Fenty Beauty Pro Filt’r Foundation – 420',
    category: 'Foundation',
    price: 48.00,
    oldPrice: 58.00,
    image: 'https://www.temptalia.com/wp-content/uploads/2018/06/fenty-beauty_420_001_product.jpg',
    rating: 4.8,
    reviews: 342,
    description: 'Luxurious foundation with silk-like finish for all skin types',
    availability: 'In Stock',
    sku: 'LSF-001',
    brand: 'Fenty Beauty',
    tags: ['foundation', 'face', 'bestseller'],
    discount: 17
  },
  {
    id: 2,
    name: 'Maybelline Instant Age Rewind Concealer',
    category: 'Concealer',
    price: 32.00,
    oldPrice: 42.00,
    image: 'https://m.media-amazon.com/images/I/612ic0cRalL.jpg',
    rating: 4.7,
    reviews: 289,
    description: 'Full coverage concealer that lasts all day',
    availability: 'In Stock',
    sku: 'PCC-002',
    brand: 'Maybelline',
    tags: ['concealer', 'face', 'bestseller'],
    discount: 24
  },
  {
    id: 3,
    name: 'Radiant Glow Primer',
    category: 'Primer',
    price: 38.00,
    oldPrice: null,
    image: 'https://credobeautydsa-com.myshopify.com/cdn/shop/products/Product_Image_-_Radiant_Glow_Primer_1080x.jpg?v=1597567467',
    rating: 4.6,
    reviews: 156,
    description: 'Silky primer that creates the perfect base for makeup',
    availability: 'In Stock',
    sku: 'RGP-003',
    brand: 'Crop Natural',
    tags: ['primer', 'face', 'new'],
    discount: 0
  },
  {
    id: 4,
    name: 'MAC Studio Fix Powder Plus Foundation',
    category: 'Foundation',
    price: 42.00,
    oldPrice: 52.00,
    image: 'https://thebeautyboxgh.com/wp-content/uploads/2021/05/4709C3A2-55FA-4637-BEC9-E6664B00862E.jpeg',
    rating: 4.5,
    reviews: 198,
    description: 'Lightweight powder foundation for natural coverage',
    availability: 'In Stock',
    sku: 'VPF-004',
    brand: 'MAC',
    tags: ['foundation', 'face'],
    discount: 19
  },
  {
    id: 5,
    name: 'Flawless Setting Spray',
    category: 'Setting Spray',
    price: 28.00,
    oldPrice: 35.00,
    image: 'https://m.media-amazon.com/images/I/61qEcvOT1OL._SL1280_.jpg',
    rating: 4.7,
    reviews: 267,
    description: 'Long-lasting setting spray for all-day makeup wear',
    availability: 'In Stock',
    sku: 'FSS-005',
    brand: 'Charlotte Tilbury',
    tags: ['setting spray', 'face', 'bestseller'],
    discount: 20
  },

  // EYES - EYESHADOW & EYELINER
  {
    id: 6,
    name: 'Luxe Eyeshadow Palette - Neutrals',
    category: 'Eyeshadow',
    price: 55.00,
    oldPrice: 70.00,
    image: 'https://i5.walmartimages.com/asr/f6d2e174-b12b-4fc1-ae39-2bf42dc6119b.7f946f0f8827d872cf543612cc79d572.jpeg',
    rating: 4.9,
    reviews: 512,
    description: '12 neutral shades with buttery texture and long wear',
    availability: 'In Stock',
    sku: 'LEP-006',
    brand: 'Luxe',
    tags: ['eyeshadow', 'eyes', 'bestseller'],
    discount: 21
  },
  {
    id: 7,
    name: 'NYX Epic Ink Liner',
    category: 'Eyeliner',
    price: 22.00,
    oldPrice: 28.00,
    image: 'https://m.media-amazon.com/images/I/71CXjKXE+4L._SL1500_.jpg',
    rating: 4.6,
    reviews: 234,
    description: 'Ultra-precise felt-tip eyeliner for perfect lines',
    availability: 'In Stock',
    sku: 'PEP-007',
    brand: 'NYX',
    tags: ['eyeliner', 'eyes'],
    discount: 21
  },
  {
    id: 8,
    name: 'L’Oréal Lash Paradise Mascara',
    category: 'Mascara',
    price: 32.00,
    oldPrice: 42.00,
    image: 'https://static.beautytocare.com/cdn-cgi/image/f=auto/media/catalog/product//l/-/l-oreal-paris-lash-paradise-volumising-mascara-01-intense-black-6-4ml_1.jpg',
    rating: 4.8,
    reviews: 401,
    description: 'Buildable mascara for dramatic volume and length',
    availability: 'In Stock',
    sku: 'VM-008',
    brand: "L’Oréal",
    tags: ['mascara', 'eyes', 'bestseller'],
    discount: 24
  },
  {
    id: 9,
    name: 'Eyebrow Pencil - Dark Brown',
    category: 'Eyebrow',
    price: 18.00,
    oldPrice: 24.00,
    image: 'https://www.tjbeautyproducts.co.uk/cdn/shop/files/Vital-DB-Eyebrow.webp?v=1726766690&width=1200',
    rating: 4.5,
    reviews: 145,
    description: 'Precision eyebrow pencil with fine tip',
    availability: 'In Stock',
    sku: 'EBP-009',
    brand: 'Vital',
    tags: ['eyebrow', 'eyes'],
    discount: 25
  },
  {
    id: 10,
    name: 'Huda Beauty Nude Obsessions Palette',
    category: 'Eyeshadow',
    price: 58.00,
    oldPrice: 75.00,
    image: 'https://hudabeauty.com/cdn/shop/files/PDP-SECTION1-NUDEOBSESSIONS-NUDELIGHT-TILE1.webp?v=1762689454&width=1946',
    rating: 4.7,
    reviews: 289,
    description: '12 rich jewel-toned shades for bold looks',
    availability: 'In Stock',
    sku: 'EJT-010',
    brand: 'Huda Beauty',
    tags: ['eyeshadow', 'eyes', 'new'],
    discount: 23
  },

  // LIPS
  {
    id: 11,
    name: 'MAC Matte Lipstick – Ruby Woo (Lipstick)',
    category: 'Lipstick',
    price: 28.00,
    oldPrice: 36.00,
    image: 'https://cdn.fynd.com/v2/falling-surf-7c8bb8/fyprod/wrkr/products/pictures/item/free/original/000000000494434929/fhBtXgY_Kw1A-000000000494434929_1.jpg',
    rating: 4.8,
    reviews: 378,
    description: 'Luxurious velvet matte lipstick with rich color',
    availability: 'In Stock',
    sku: 'VLS-011',
    brand: 'MAC',
    tags: ['lipstick', 'lips', 'bestseller'],
    discount: 22
  },
  {
    id: 12,
    name: 'Fenty Beauty Gloss Bomb Heat',
    category: 'Lip Gloss',
    price: 22.00,
    oldPrice: 28.00,
    image: 'https://www.cultbeauty.com/images?url=https://static.thcdn.com/productimg/original/15654153-1355209564678047.jpg&format=webp&auto=avif&width=985&height=985&fit=cover',
    rating: 4.6,
    reviews: 267,
    description: 'Shimmering lip gloss with plumping effect',
    availability: 'In Stock',
    sku: 'GLG-012',
    brand: 'Fenty Beauty',
    tags: ['lip gloss', 'lips'],
    discount: 21
  },
  {
    id: 13,
    name: 'Dior Addict Lip Glow Oil',
    category: 'Lip oil',
    price: 16.00,
    oldPrice: 22.00,
    image: 'https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw3561edaa/Y0000163/Y0000163_E000001063_E01_ZHC.jpg?sw=1800',
    rating: 4.5,
    reviews: 134,
    description: 'Precision lip liner for defined lips',
    availability: 'In Stock',
    sku: 'LLN-013',
    brand: 'Dior',
    tags: ['lip oil', 'lips'],
    discount: 27
  },
  {
    id: 14,
    name: 'Maybelline SuperStay Matte Ink – Pioneer',
    category: 'Lipstick',
    price: 26.00,
    oldPrice: 34.00,
    image: 'https://cdn.salla.sa/onxjbX/94ac6edd-3400-4ac4-8363-2ac7827d3826-1000x1000-YOoWyaJBMLNDfTe9ZIJokqI1fs9QSCBG0VFYOuHd.png',
    rating: 4.7,
    reviews: 245,
    description: 'Long-wearing liquid lipstick with matte finish',
    availability: 'In Stock',
    sku: 'LLS-014',
    brand: 'Maybelline',
    tags: ['lipstick', 'lips'],
    discount: 24
  },
  {
    id: 15,
    name: 'Lip Balm - Rose',
    category: 'Lip Care',
    price: 14.00,
    oldPrice: null,
    image: 'https://static.beautytocare.com/media/catalog/product/l/a/labello-soft-rose-lip-balm-4-8g.jpg',
    rating: 4.4,
    reviews: 89,
    description: 'Nourishing lip balm with natural rose scent',
    availability: 'In Stock',
    sku: 'LBR-015',
    brand: 'Labello',
    tags: ['lip care', 'lips', 'new'],
    discount: 0
  },

  // CHEEKS - BLUSH & BRONZER
  {
    id: 16,
    name: 'Silky Blush - Coral Peach',
    category: 'Blush',
    price: 32.00,
    oldPrice: 42.00,
    image: 'https://assets.kmart.com.au/transform/c37eda0b-87ff-4d4b-8c22-f0d48be8ad98/43637058-1?io=transform:fit,width:3840,height:4800&quality=90',
    rating: 4.7,
    reviews: 312,
    description: 'Smooth blush with natural flush finish',
    availability: 'In Stock',
    sku: 'SBC-016',
    brand: 'Kmart',
    tags: ['blush', 'cheeks', 'bestseller'],
    discount: 24
  },
  {
    id: 17,
    name: 'NARS Bronzing Powder',
    category: 'Bronzer',
    price: 36.00,
    oldPrice: 46.00,
    image: 'https://www.narscosmetics.ca/on/demandware.static/-/Sites-itemmaster_NARS/default/dw299f43fd/2023/March/Makeup/LagunaBronzer/Swatches/999NAC0000155_BronzingPowder_Laguna02_1.jpg',
    rating: 4.6,
    reviews: 198,
    description: 'Matte bronzer for natural sun-kissed glow',
    availability: 'In Stock',
    sku: 'BP-017',
    brand: 'NARS',
    tags: ['bronzer', 'cheeks'],
    discount: 22
  },
  {
    id: 18,
    name: 'Highlighter Palette',
    category: 'Highlighter',
    price: 42.00,
    oldPrice: 55.00,
    image: 'https://www.paccosmetics.com/cdn/shop/files/8904341211946_IMG.main.jpg?v=1760003494',
    rating: 4.8,
    reviews: 289,
    description: '4 luminous highlighter shades for radiant skin',
    availability: 'In Stock',
    sku: 'HP-018',
    brand: 'PAC Cosmetics',
    tags: ['highlighter', 'cheeks', 'bestseller'],
    discount: 24
  },
  {
    id: 19,
    name: 'Cream Blush - Rosy Pink',
    category: 'Blush',
    price: 28.00,
    oldPrice: 36.00,
    image: 'https://besamecosmetics.com/cdn/shop/files/Rose_Pink_classic_rosy_pink.jpg?v=1757478029&width=1080',
    rating: 4.5,
    reviews: 167,
    description: 'Creamy blush for seamless blending',
    availability: 'In Stock',
    sku: 'CB-019',
    brand: 'Besame Cosmetics',
    tags: ['blush', 'cheeks'],
    discount: 22
  },
  {
    id: 20,
    name: 'Contour Kit',
    category: 'Contour',
    price: 45.00,
    oldPrice: 60.00,
    image: 'https://static.beautytocare.com/cdn-cgi/image/width=1600,height=1600,f=auto/media/catalog/product//m/a/makeup-revolution-ultra-sculpt-contour-kit-ultra-fair-c01.jpg',
    rating: 4.7,
    reviews: 234,
    description: '6 shades for professional contouring',
    availability: 'In Stock',
    sku: 'CK-020',
    brand: 'Revolution',
    tags: ['contour', 'cheeks', 'new'],
    discount: 25
  },

  // SKINCARE
  {
    id: 21,
    name: 'La Roche-Posay Effaclar Cleanser',
    category: 'Cleanser',
    price: 38.00,
    oldPrice: 48.00,
    image: 'https://thebeautyboxgh.com/wp-content/uploads/2023/03/BD27D97D-0D73-43CF-8385-E25EB866B78A.jpeg.webp',
    rating: 4.6,
    reviews: 201,
    description: 'Gentle yet effective facial cleanser',
    availability: 'In Stock',
    sku: 'LFC-021',
    brand: 'La Roche-Posay',
    tags: ['skincare', 'cleanser'],
    discount: 21
  },
  {
    id: 22,
    name: 'Simple Kind to Skin Moisturizer',
    category: 'Moisturizer',
    price: 52.00,
    oldPrice: 68.00,
    image: 'https://images-cdn.ubuy.co.in/6639a2ba9985395585317bc2-hydrating-light-moisturiser-lotion-125ml.jpg',
    rating: 4.8,
    reviews: 345,
    description: 'Rich moisturizer for all skin types',
    availability: 'In Stock',
    sku: 'HM-022',
    brand: 'Simple Cosmetics',
    tags: ['skincare', 'moisturizer', 'bestseller'],
    discount: 24
  },
  {
    id: 23,
    name: 'Vitamin C Serum',
    category: 'Serum',
    price: 65.00,
    oldPrice: 85.00,
    image: 'https://naturaloilbar.com/wp-content/uploads/2022/11/11583_GARNIER_VIT-C-SERUM-BOTTLE-V1-copy.jpg',
    rating: 4.7,
    reviews: 267,
    description: 'Brightening serum with pure vitamin C',
    availability: 'In Stock',
    sku: 'VCS-023',
    brand: 'Garnier',
    tags: ['skincare', 'serum'],
    discount: 24
  },
  {
    id: 24,
    name: 'Anti-Aging Eye Cream',
    category: 'Eye Cream',
    price: 48.00,
    oldPrice: 62.00,
    image: 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/loe/loe64219/y/12.jpg',
    rating: 4.6,
    reviews: 178,
    description: 'Delicate eye cream to reduce fine lines',
    availability: 'In Stock',
    sku: 'AAE-024',
    brand: "L'Oreal'",
    tags: ['skincare', 'eye cream'],
    discount: 23
  },
  {
    id: 25,
    name: 'Freeman Exfoliating Face Mask',
    category: 'Mask',
    price: 42.00,
    oldPrice: 55.00,
    image: 'https://i5.walmartimages.com/seo/Freeman-Exfoliating-Charcoal-Coconut-Facial-Scrub-Wash-off-Mask-for-Dry-Skin-3-fl-oz-Tube_1053ebe9-4ed9-4185-b78e-8c1a43c2015f.7b1e6a04d5c429b3eed5e66c08dd679c.jpeg',
    rating: 4.5,
    reviews: 145,
    description: 'Weekly exfoliating treatment for smooth skin',
    availability: 'In Stock',
    sku: 'EFM-025',
    brand: 'Freeman',
    tags: ['skincare', 'mask'],
    discount: 24
  },

  // BRUSHES & TOOLS
  {
    id: 26,
    name: 'Real Techniques Makeup Brush Set',
    category: 'Brushes',
    price: 85.00,
    oldPrice: 110.00,
    image: 'https://i5.walmartimages.com/seo/Real-Techniques-Travel-Essentials-2-0-Makeup-Brush-Set-3PC_c0e14b7b-b75b-428b-857f-a96097336dc2.6be4ac5e7dabf5d75301e928b3736ad7.jpeg',
    rating: 4.8,
    reviews: 289,
    description: 'Complete brush set with premium synthetic bristles',
    availability: 'In Stock',
    sku: 'PBS-026',
    brand: 'Real Techniques',
    tags: ['brushes', 'tools', 'bestseller'],
    discount: 23
  },
  {
    id: 27,
    name: 'Beauty Blender Makeup Sponge',
    category: 'Sponges',
    price: 16.00,
    oldPrice: 22.00,
    image: 'https://www.paccosmetics.com/cdn/shop/files/8904341201046_IMG.main.jpg?v=1765457672',
    rating: 4.4,
    reviews: 98,
    description: 'Latex-free makeup sponges for flawless application',
    availability: 'In Stock',
    sku: 'MS-027',
    brand: 'Beauty Cosmetics',
    tags: ['sponges', 'tools'],
    discount: 27
  },
  {
    id: 28,
    name: 'STYLPRO Brush Cleaner & Dryer',
    category: 'Tools',
    price: 35.00,
    oldPrice: null,
    image: 'https://static.beautytocare.com/cdn-cgi/image/width=1600,height=1600,f=auto/media/catalog/product//s/t/stylpro-makeup-brush-cleaner-gift-set-blush_1.png',
    rating: 4.6,
    reviews: 123,
    description: 'Electric brush cleaner and dryer',
    availability: 'In Stock',
    sku: 'BCD-028',
    brand: 'STYLEPRO',
    tags: ['tools', 'new'],
    discount: 0
  },
  {
    id: 29,
    name: 'Prime Makeup Brush Holder',
    category: 'Storage',
    price: 28.00,
    oldPrice: 36.00,
    image: 'https://primepick.co.in/cdn/shop/files/131.jpg?v=1765889170',
    rating: 4.5,
    reviews: 87,
    description: 'Elegant brush holder with compartments',
    availability: 'In Stock',
    sku: 'MBH-029',
    brand: 'Prime',
    tags: ['storage', 'tools'],
    discount: 22
  },
  {
    id: 30,
    name: 'Eyelash Curler',
    category: 'Tools',
    price: 18.00,
    oldPrice: 24.00,
    image: 'https://static.beautytocare.com/media/catalog/product/b/r/brushworks-eyelash-curler-pink.jpg',
    rating: 4.7,
    reviews: 156,
    description: 'Professional-grade eyelash curler',
    availability: 'In Stock',
    sku: 'EC-030',
    brand: 'Brushworks',
    tags: ['tools', 'eyes'],
    discount: 25
  },

  // NAIL CARE
  {
    id: 31,
    name: 'Nail Polish - Midnight Black',
    category: 'Nail Polish',
    price: 12.00,
    oldPrice: 16.00,
    image: 'https://static.beautytocare.com/cdn-cgi/image/width=1600,height=1600,f=auto/media/catalog/product//c/a/catrice-gel-affair-nail-polish-044-sparkle-like-it-s-midnight-10-5ml-3.jpg',
    rating: 4.6,
    reviews: 134,
    description: 'Long-lasting nail polish with gel-like finish',
    availability: 'In Stock',
    sku: 'NP-031',
    brand: 'Catrice',
    tags: ['nail polish', 'nails'],
    discount: 25
  },
  {
    id: 32,
    name: 'Gel Nail Polish - Rose Gold',
    category: 'Gel Polish',
    price: 18.00,
    oldPrice: 24.00,
    image: 'https://media.ilnp.com/uploads/2015/11/juliette-rose-gold-holographic-ultra-metallic-nail-polish-10.jpg',
    rating: 4.7,
    reviews: 201,
    description: 'UV gel polish for salon-quality nails',
    availability: 'In Stock',
    sku: 'GP-032',
    brand: 'ILNP',
    tags: ['gel polish', 'nails'],
    discount: 25
  },
  {
    id: 33,
    name: 'Nail File Set',
    category: 'Nail Tools',
    price: 14.00,
    oldPrice: 18.00,
    image: 'https://m.media-amazon.com/images/I/61lLBqssEjL._SX679_.jpg',
    rating: 4.4,
    reviews: 76,
    description: 'Professional nail file set with 5 files',
    availability: 'In Stock',
    sku: 'NFS-033',
    brand: 'haichuang',
    tags: ['nail tools', 'nails'],
    discount: 22
  },
  {
    id: 34,
    name: 'Cuticle Oil',
    category: 'Nail Care',
    price: 16.00,
    oldPrice: 22.00,
    image: 'https://i.etsystatic.com/7029989/r/il/6a5c57/6414764024/il_fullxfull.6414764024_l6ox.jpg',
    rating: 4.5,
    reviews: 98,
    description: 'Nourishing cuticle oil with natural ingredients',
    availability: 'In Stock',
    sku: 'CO-034',
    brand: 'Etsy',
    tags: ['nail care', 'nails'],
    discount: 27
  },
  {
    id: 35,
    name: 'Nail Art Brush Set',
    category: 'Nail Tools',
    price: 22.00,
    oldPrice: 28.00,
    image: 'https://i-spa.co.za/cdn/shop/products/15pcartbrushset2.jpg?v=1667494886',
    rating: 4.6,
    reviews: 112,
    description: 'Precision brushes for nail art designs',
    availability: 'In Stock',
    sku: 'NAB-035',
    brand: 'iSpa',
    tags: ['nail tools', 'nails'],
    discount: 21
  },

  // FRAGRANCE
  {
    id: 36,
    name: 'Dior Sauvage Eau de Parfum',
    category: 'Perfume',
    price: 78.00,
    oldPrice: 98.00,
    image: 'https://m.media-amazon.com/images/I/51Hxl7J1jzL._SL1024_.jpg',
    rating: 4.8,
    reviews: 267,
    description: 'Luxurious floral fragrance with long-lasting scent',
    availability: 'In Stock',
    sku: 'EDP-036',
    brand: 'Christian Dior',
    tags: ['perfume', 'fragrance', 'bestseller'],
    discount: 20
  },
  {
    id: 37,
    name: 'Body Mist - Vanilla',
    category: 'Body Mist',
    price: 28.00,
    oldPrice: 36.00,
    image: 'https://everythingbeautygh.com/wp-content/uploads/4097.jpg',
    rating: 4.5,
    reviews: 145,
    description: 'Light and refreshing body mist',
    availability: 'In Stock',
    sku: 'BM-037',
    brand: 'Bath and Body Works',
    tags: ['body mist', 'fragrance'],
    discount: 22
  },
  {
    id: 38,
    name: 'Fragrance Roller - Amber',
    category: 'Fragrance',
    price: 18.00,
    oldPrice: 24.00,
    image: 'https://www.flameelegancecandles.com/cdn/shop/files/perfume-phalate-free-amber-noir-scent-flame-elegance.jpg?v=1777051549',
    rating: 4.4,
    reviews: 89,
    description: 'Portable fragrance roller for on-the-go',
    availability: 'In Stock',
    sku: 'FR-038',
    brand: 'Ana\'s Cosmetics',
    tags: ['fragrance', 'new'],
    discount: 25
  }, 
  {
    id: 39,
    name: 'Cranberry Scented Candle',
    category: 'Home Fragrance',
    price: 32.00,
    oldPrice: 42.00,
    image: 'https://market99.com/cdn/shop/files/1_06a7da02-f64c-4958-a584-91ba069d3fee.jpg?v=1750156058',
    rating: 4.6,
    reviews: 178,
    description: 'Premium scented candle with 40-hour burn time',
    availability: 'In Stock',
    sku: 'SC-039',
    brand: 'MARKET99',
    tags: ['candle', 'home fragrance'],
    discount: 24
  },
  {
    id: 40,
    name: 'Perfume Sampler Set',
    category: 'Perfume',
    price: 45.00,
    oldPrice: 60.00,
    image: 'https://www.providenceperfume.com/cdn/shop/products/0005_WEBProvPerfume2022.11.01_7L6A7086.jpg?v=1668874682',
    rating: 4.7,
    reviews: 201,
    description: '5 fragrance samples to discover your favorite',
    availability: 'In Stock',
    sku: 'PS-040',
    brand: 'Ana\'s Cosmetics',
    tags: ['perfume', 'fragrance'],
    discount: 25
  },

  // HAIR CARE
  {
    id: 41,
    name: 'Silk Hair Serum',
    category: 'Hair Serum',
    price: 32.00,
    oldPrice: 42.00,
    image: 'https://static.beautytocare.com/media/catalog/product/a/r/arganicare-silk-fortifying-hair-serum-100ml.jpg',
    rating: 4.7,
    reviews: 234,
    description: 'Smoothing serum for silky, frizz-free hair',
    availability: 'In Stock',
    sku: 'SHS-041',
    brand: 'Arganicare',
    tags: ['hair serum', 'hair care'],
    discount: 24
  },
  {
    id: 42,
    name: 'Coconut & Hibiscus Curl Shampoo',
    category: 'Shampoo',
    price: 28.00,
    oldPrice: 36.00,
    image: 'https://i5.walmartimages.com/seo/SheaMoisture-Curl-Shine-Shampoo-Coconut-Hibiscus-16-Oz_84bc6861-991c-489a-9b53-5e6bc1089a1f.22a0ebd76807d37708c6e57bcc7ce870.jpeg',
    rating: 4.5,
    reviews: 167,
    description: 'Lightweight shampoo for fuller, thicker hair',
    availability: 'In Stock',
    sku: 'VS-042',
    brand: 'SheaMoisture',
    tags: ['shampoo', 'hair care'],
    discount: 22
  },
  {
    id: 43,
    name: 'Curl & Shine Conditioner',
    category: 'Conditioner',
    price: 28.00,
    oldPrice: 36.00,
    image: 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/smt/smt29062/l/30.jpg',
    rating: 4.6,
    reviews: 189,
    description: 'Deep conditioning treatment for dry hair',
    availability: 'In Stock',
    sku: 'HC-043',
    brand: 'SheaMoisture',
    tags: ['conditioner', 'hair care'],
    discount: 22
  },
  {
    id: 44,
    name: 'Hair Mask - Repair',
    category: 'Hair Mask',
    price: 35.00,
    oldPrice: 45.00,
    image: 'https://static.beautytocare.com/media/catalog/product/l/-/l-oreal-paris-elvive-total-repair-5-hair-mask-300ml_2.jpg',
    rating: 4.7,
    reviews: 212,
    description: 'Intensive repair mask for damaged hair',
    availability: 'In Stock',
    sku: 'HM-044',
    brand: "L'Oréal Paris",
    tags: ['hair mask', 'hair care'],
    discount: 22
  },
  {
    id: 45,
    name: 'Rosemary Mint Strengthening Shampoo',
    category: 'Dry Shampoo',
    price: 18.00,
    oldPrice: 24.00,
    image: 'https://gh.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/89/5855003/1.jpg?7354',
    rating: 4.4,
    reviews: 134,
    description: 'Refreshing dry shampoo for between washes',
    availability: 'In Stock',
    sku: 'DS-045',
    brand: 'Mielle',
    tags: ['dry shampoo', 'hair care'],
    discount: 25
  },

  // BODY CARE
  {
    id: 46,
    name: 'Dove Nourishing Body Care Lotion',
    category: 'Body Lotion',
    price: 38.00,
    oldPrice: 48.00,
    image: 'https://www.chopboxonline.com/wp-content/uploads/2021/06/dove-nourishing-body-lotion-400ml.webp',
    rating: 4.6,
    reviews: 201,
    description: 'Silky body lotion with luxurious fragrance',
    availability: 'In Stock',
    sku: 'LBL-046',
    brand: 'Dove',
    tags: ['body lotion', 'body care'],
    discount: 21
  },
  {
    id: 47,
    name: 'Shea Sugar Scrub',
    category: 'Body Scrub',
    price: 32.00,
    oldPrice: 42.00,
    image: 'https://static.beautytocare.com/media/catalog/product/t/r/tree-hut-watermelon-shea-sugar-scrub-510g.jpg',
    rating: 4.5,
    reviews: 156,
    description: 'Gentle exfoliating body scrub with sugar crystals',
    availability: 'In Stock',
    sku: 'BS-047',
    brand: 'Tree Hut',
    tags: ['body scrub', 'body care'],
    discount: 24
  },
  {
    id: 48,
    name: 'Hand Cream - Rose',
    category: 'Hand Care',
    price: 18.00,
    oldPrice: 24.00,
    image: 'https://i5.walmartimages.com/seo/Bath-Body-Works-Hand-Cream-ROSE-Clean-Playful-Light-Blend-Airy-Rose-Water-Jasmine-Petals-Amp-Creamy-Musk-Deeply-Moisturizing-Hand-Cream_adfb2962-690b-45bf-a1a5-3460232ef328.6a531f5a16cffb1f04687a1f08d8aa77.jpeg',
    rating: 4.4,
    reviews: 112,
    description: 'Nourishing hand cream with rose extract',
    availability: 'In Stock',
    sku: 'HC-048',
    brand: 'Bath And Body Works',
    tags: ['hand cream', 'body care'],
    discount: 25
  },
  {
    id: 49,
    name: 'Bath Bomb Set',
    category: 'Bath',
    price: 35.00,
    oldPrice: 45.00,
    image: 'https://www.naplessoap.com/cdn/shop/files/Bath_Bomb_Set_Lifestyle-min__16271.1712689527.1280.1280.jpg?v=1773786344',
    rating: 4.7,
    reviews: 189,
    description: '4 luxurious bath bombs with essential oils',
    availability: 'In Stock',
    sku: 'BB-049',
    brand: 'Ana\'s Cosmetics',
    tags: ['bath bomb', 'body care'],
    discount: 22
  },
  {
    id: 50,
    name: 'Body Oil - Shimmer',
    category: 'Body Oil',
    price: 42.00,
    oldPrice: 55.00,
    image: 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/pal/pal04171/y/8.jpg',
    rating: 4.6,
    reviews: 145,
    description: 'Shimmering body oil for luminous skin',
    availability: 'In Stock',
    sku: 'BO-050',
    brand: "Palmer's",
    tags: ['body oil', 'body care'],
    discount: 24
  },

  // SETS & BUNDLES
  {
    id: 51,
    name: 'Complexion Essentials',
    category: 'Sets',
    price: 125.00,
    oldPrice: 165.00,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeGbDQeidlC1c2aMvkegcQWF2ftGHo0dyRLQs3PIJqBPLU8ZHMKZJDm_A&s=10',
    rating: 4.8,
    reviews: 312,
    description: 'Everything you need to start your makeup journey',
    availability: 'In Stock',
    sku: 'CMS-051',
    brand: 'Fenty Beauty',
    tags: ['sets', 'bestseller'],
    discount: 24
  },
  {
    id: 52,
    name: 'Everyday Essentials Brush Set',
    category: 'Sets',
    price: 145.00,
    oldPrice: 190.00,
    image: 'https://realtechniques.com/cdn/shop/files/1786_RT_EverydayEssentialsSet_Front_300dpiRGB.jpg?v=1683303836&width=4096',
    rating: 4.7,
    reviews: 234,
    description: 'Complete skincare routine in one bundle',
    availability: 'In Stock',
    sku: 'SEB-052',
    brand: 'Real Techniques',
    tags: ['sets', 'skincare'],
    discount: 24
  },
  {
    id: 53,
    name: 'Lip Collection - 5 Colors',
    category: 'Sets',
    price: 95.00,
    oldPrice: 125.00,
    image: 'https://cdn.platform.next/common/items/default/default/itemimages/3_4Ratio/product/lge/B40956s2.jpg',
    rating: 4.6,
    reviews: 178,
    description: '5 must-have lipstick shades',
    availability: 'In Stock',
    sku: 'LC-053',
    brand: 'Victoria Secret',
    tags: ['sets', 'lips'],
    discount: 24
  },
  {
    id: 54,
    name: 'Eye Makeup Collection',
    category: 'Sets',
    price: 135.00,
    oldPrice: 175.00,
    image: 'https://colorsqueen.com/cdn/shop/files/01_443d455f-ef97-4cc3-8568-795308105f45.jpg?v=1742881788&width=1500',
    rating: 4.7,
    reviews: 201,
    description: 'Complete eye makeup set with palettes and tools',
    availability: 'In Stock',
    sku: 'EMC-054',
    brand: 'Ana\'s Cosmetics',
    tags: ['sets', 'eyes'],
    discount: 23
  },
  {
    id: 55,
    name: 'Luxury Gift Set',
    category: 'Sets',
    price: 185.00,
    oldPrice: 245.00,
    image: 'https://www.brillare.co.in/cdn/shop/files/Rose-Royale-2_85e5b0a8-9284-4b84-b93e-710dfd0462a9.jpg?v=1731061487&width=416',
    rating: 4.9,
    reviews: 289,
    description: 'Premium gift set with bestselling products',
    availability: 'In Stock',
    sku: 'LGS-055',
    brand: 'Ana\'s Cosmetics',
    tags: ['sets', 'gift', 'bestseller'],
    discount: 24
  },

  // ADDITIONAL PRODUCTS
  {
    id: 56,
    name: 'Makeup Remover Wipes',
    category: 'Makeup Remover',
    price: 14.00,
    oldPrice: 18.00,
    image: 'https://i5.walmartimages.com/seo/Neutrogena-Hydro-Boost-Makeup-Remover-Wipes-Face-Cleansing-Towelettes-25-Count_c3027e0d-7f91-4c13-8d13-d2ba409985b5.f6844aea8f9da11e96c462e998fbc2ed.jpeg',
    rating: 4.5,
    reviews: 123,
    description: 'Gentle makeup remover wipes for sensitive skin',
    availability: 'In Stock',
    sku: 'MRW-056',
    brand: 'Neutrogena',
    tags: ['makeup remover', 'skincare'],
    discount: 22
  },
  {
    id: 57,
    name: 'Toner - Hydrating',
    category: 'Toner',
    price: 35.00,
    oldPrice: 45.00,
    image: 'https://gh.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/41/9235003/1.jpg?7088',
    rating: 4.6,
    reviews: 145,
    description: 'Hydrating toner to balance skin',
    availability: 'In Stock',
    sku: 'TH-057',
    brand: 'FaceFacts',
    tags: ['toner', 'skincare'],
    discount: 22
  },
  {
    id: 58,
    name: 'Face Mist - Rose Water',
    category: 'Face Mist',
    price: 22.00,
    oldPrice: 28.00,
    image: 'https://i5.walmartimages.com/seo/Rosewater-Refreshing-Facial-Mist-2-fl-oz-for-All-Skin-Types-by-Heritage-Store_ff97da97-5a20-4e9e-bc5a-5a7cbe0e2b03.15c2de6d892ea81ec8456fed5b728bc8.png',
    rating: 4.4,
    reviews: 98,
    description: 'Refreshing rose water face mist',
    availability: 'In Stock',
    sku: 'FMR-058',
    brand: 'Heritagestore',
    tags: ['face mist', 'skincare'],
    discount: 21
  },
  {
    id: 59,
    name: 'Sunscreen SPF 50',
    category: 'Sunscreen',
    price: 38.00,
    oldPrice: 48.00,
    image: 'https://perfumegh.com/wp-content/uploads/2025/02/s-l1200-1.jpg',
    rating: 4.7,
    reviews: 212,
    description: 'Lightweight daily sunscreen with SPF 50',
    availability: 'In Stock',
    sku: 'SS-059',
    brand: 'Cerave',
    tags: ['sunscreen', 'skincare'],
    discount: 21
  },
  {
    id: 60,
    name: 'Night Cream - Repair',
    category: 'Night Cream',
    price: 52.00,
    oldPrice: 68.00,
    image: 'https://i5.walmartimages.com/seo/Equate-Triple-Repair-Moisturizer-Night-Cream-All-Skin-Types-Dryness-1-7-oz_dcc4fc59-e726-416c-80cd-96b1bf68f898.724a0994f25095d69545404ac5a1ad80.jpeg',
    rating: 4.8,
    reviews: 267,
    description: 'Rich night cream for overnight repair',
    availability: 'In Stock',
    sku: 'NC-060',
    brand: 'Equate',
    tags: ['night cream', 'skincare', 'bestseller'],
    discount: 24
  }
];

// Get product by ID
function getProductById(id) {
  return PRODUCTS.find(p => p.id === id);
}

// Get products by category
function getProductsByCategory(category) {
  return PRODUCTS.filter(p => p.category === category);
}

// Get all categories
function getCategories() {
  return [...new Set(PRODUCTS.map(p => p.category))].sort();
}

// Search products
function searchProducts(query) {
  const q = query.toLowerCase();
  return PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q) ||
    p.tags.some(tag => tag.toLowerCase().includes(q))
  );
}

// Get featured products
function getFeaturedProducts(limit = 6) {
  return PRODUCTS.filter(p => p.tags.includes('bestseller')).slice(0, limit);
}

// Get new products
function getNewProducts(limit = 6) {
  return PRODUCTS.filter(p => p.tags.includes('new')).slice(0, limit);
}

// Get sale products
function getSaleProducts() {
  return PRODUCTS.filter(p => p.discount > 0).sort((a, b) => b.discount - a.discount);
}
